### ISSUE TITLE
angular4-weui 使用文档不清晰

### ISSUE THREAD

**Issue by ForrestGumpForever** [fbchen/angular4-weui#1]
angular4-weui 使用文档不清晰：
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';

import { WeUIModule } from 'angular4-weui';

import { AppComponent }   from './app.component';

@NgModule({
    imports: [
        FormsModule,
        BrowserModule,
        WeUIModule
    ],
    declarations: [
        AppComponent
    ],
    providers: [],
    bootstrap: [ AppComponent ]
})
export class AppModule { }

然后 ，怎么去使用呢？
https://github.com/fbchen/angular4-weui-demo 也打不开！

**Comment by fbchen** [comment]
在线例子：https://fbchen.github.io/angular4-weui/
如何搭建Angular工程，可以使用Angular CLI来快速搭建一个Angular工程，请参考：
http://origin.angular.live/docs/ts/latest/cli-quickstart.html
